version: 1.0.{build}
environment:
  azure_appid:
    secure: D7Y34Ll8rhVi1lK88P7JmqbrIVSFWxZyJoNLlYOB9WLgKFsIDEtbn6wSo8RvW/OS
  azure_tenantid:
    secure: KCL9ycA5gzAXY9v95PtDFfhHZ7C5I3wtYKsmeuHnhLSlYarOaJsbQOWa8Yz70zEp
  azure_pass:
    secure: 2gr9tKR6nevzTNEVnxJ2ESzkqeqGjBHQjj8pFqA3HLIQKEMAMFFHbuN5d9nQuTYg
  azure_subscriptionid:
    secure: aFoy5cVzMvbJwz9DNvL0LMQJP5NyifyUBvx/3R8lB2UJsopMCuFe9Bw8Z91AOVtD
  vm_admin_pass:
    secure: Ry2UOyp9ENPf/FeUv5KJWw==
image: WMF 5
install:
- ps: .\buildscripts\install.ps1
build_script:
- ps: .\buildscripts\build.ps1
test_script:
- ps: .\buildscripts\test.ps1